//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class FMDataDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.FMData>
    {
    
        public FMDataDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).FMData;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class FMDataServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.FMData>
    {
        public FMDataServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.APP))
            {
                return new global::LightSwitchApplication.Implementation.APP();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.REF_APPLICATION_TYPE))
            {
                return new global::LightSwitchApplication.Implementation.REF_APPLICATION_TYPE();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.REF_COMPLEXITY))
            {
                return new global::LightSwitchApplication.Implementation.REF_COMPLEXITY();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.REF_DOCUMENT_TYPE))
            {
                return new global::LightSwitchApplication.Implementation.REF_DOCUMENT_TYPE();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.REF_GAP))
            {
                return new global::LightSwitchApplication.Implementation.REF_GAP();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.REF_PHASE))
            {
                return new global::LightSwitchApplication.Implementation.REF_PHASE();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.REF_ROLE))
            {
                return new global::LightSwitchApplication.Implementation.REF_ROLE();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.REF_STAKEHOLDER))
            {
                return new global::LightSwitchApplication.Implementation.REF_STAKEHOLDER();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.REF_STATUS))
            {
                return new global::LightSwitchApplication.Implementation.REF_STATUS();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.REF_TECHNOLOGY))
            {
                return new global::LightSwitchApplication.Implementation.REF_TECHNOLOGY();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.REF_TECHNOLOGY_STACK))
            {
                return new global::LightSwitchApplication.Implementation.REF_TECHNOLOGY_STACK();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.REF_VENDOR))
            {
                return new global::LightSwitchApplication.Implementation.REF_VENDOR();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.RESOURCE))
            {
                return new global::LightSwitchApplication.Implementation.RESOURCE();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TP_APPLICATION))
            {
                return new global::LightSwitchApplication.Implementation.TP_APPLICATION();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TP_DOCUMENT_LINK))
            {
                return new global::LightSwitchApplication.Implementation.TP_DOCUMENT_LINK();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TP_PHASE))
            {
                return new global::LightSwitchApplication.Implementation.TP_PHASE();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TP_RESOURCE_ALLOCATION))
            {
                return new global::LightSwitchApplication.Implementation.TP_RESOURCE_ALLOCATION();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TP_STAKEHOLDER))
            {
                return new global::LightSwitchApplication.Implementation.TP_STAKEHOLDER();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TP_VENDOR))
            {
                return new global::LightSwitchApplication.Implementation.TP_VENDOR();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TP))
            {
                return new global::LightSwitchApplication.Implementation.TP();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.FMData CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.FMData(this.GetEntityConnectionString(
                "FMData",
                "res://" + assemblyName + "/FMData.csdl|res://" + assemblyName + "/FMData.ssdl|res://" + assemblyName + "/FMData.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.APP))
            {
                return new global::LightSwitchApplication.Implementation.APP();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.REF_APPLICATION_TYPE))
            {
                return new global::LightSwitchApplication.Implementation.REF_APPLICATION_TYPE();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.REF_COMPLEXITY))
            {
                return new global::LightSwitchApplication.Implementation.REF_COMPLEXITY();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.REF_DOCUMENT_TYPE))
            {
                return new global::LightSwitchApplication.Implementation.REF_DOCUMENT_TYPE();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.REF_GAP))
            {
                return new global::LightSwitchApplication.Implementation.REF_GAP();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.REF_PHASE))
            {
                return new global::LightSwitchApplication.Implementation.REF_PHASE();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.REF_ROLE))
            {
                return new global::LightSwitchApplication.Implementation.REF_ROLE();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.REF_STAKEHOLDER))
            {
                return new global::LightSwitchApplication.Implementation.REF_STAKEHOLDER();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.REF_STATUS))
            {
                return new global::LightSwitchApplication.Implementation.REF_STATUS();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.REF_TECHNOLOGY))
            {
                return new global::LightSwitchApplication.Implementation.REF_TECHNOLOGY();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.REF_TECHNOLOGY_STACK))
            {
                return new global::LightSwitchApplication.Implementation.REF_TECHNOLOGY_STACK();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.REF_VENDOR))
            {
                return new global::LightSwitchApplication.Implementation.REF_VENDOR();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.RESOURCE))
            {
                return new global::LightSwitchApplication.Implementation.RESOURCE();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TP_APPLICATION))
            {
                return new global::LightSwitchApplication.Implementation.TP_APPLICATION();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TP_DOCUMENT_LINK))
            {
                return new global::LightSwitchApplication.Implementation.TP_DOCUMENT_LINK();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TP_PHASE))
            {
                return new global::LightSwitchApplication.Implementation.TP_PHASE();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION))
            {
                return new global::LightSwitchApplication.Implementation.TP_RESOURCE_ALLOCATION();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TP_STAKEHOLDER))
            {
                return new global::LightSwitchApplication.Implementation.TP_STAKEHOLDER();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TP_VENDOR))
            {
                return new global::LightSwitchApplication.Implementation.TP_VENDOR();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TP))
            {
                return new global::LightSwitchApplication.Implementation.TP();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.FMDataService))
            {
                return new global::LightSwitchApplication.FMDataService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.FMDataService))
            {
                return new global::LightSwitchApplication.Implementation.FMDataServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.APP) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.APP);
            }
            if (typeof(global::LightSwitchApplication.REF_APPLICATION_TYPE) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.REF_APPLICATION_TYPE);
            }
            if (typeof(global::LightSwitchApplication.REF_COMPLEXITY) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.REF_COMPLEXITY);
            }
            if (typeof(global::LightSwitchApplication.REF_DOCUMENT_TYPE) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.REF_DOCUMENT_TYPE);
            }
            if (typeof(global::LightSwitchApplication.REF_GAP) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.REF_GAP);
            }
            if (typeof(global::LightSwitchApplication.REF_PHASE) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.REF_PHASE);
            }
            if (typeof(global::LightSwitchApplication.REF_ROLE) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.REF_ROLE);
            }
            if (typeof(global::LightSwitchApplication.REF_STAKEHOLDER) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.REF_STAKEHOLDER);
            }
            if (typeof(global::LightSwitchApplication.REF_STATUS) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.REF_STATUS);
            }
            if (typeof(global::LightSwitchApplication.REF_TECHNOLOGY) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.REF_TECHNOLOGY);
            }
            if (typeof(global::LightSwitchApplication.REF_TECHNOLOGY_STACK) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.REF_TECHNOLOGY_STACK);
            }
            if (typeof(global::LightSwitchApplication.REF_VENDOR) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.REF_VENDOR);
            }
            if (typeof(global::LightSwitchApplication.RESOURCE) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.RESOURCE);
            }
            if (typeof(global::LightSwitchApplication.TP_APPLICATION) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TP_APPLICATION);
            }
            if (typeof(global::LightSwitchApplication.TP_DOCUMENT_LINK) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TP_DOCUMENT_LINK);
            }
            if (typeof(global::LightSwitchApplication.TP_PHASE) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TP_PHASE);
            }
            if (typeof(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TP_RESOURCE_ALLOCATION);
            }
            if (typeof(global::LightSwitchApplication.TP_STAKEHOLDER) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TP_STAKEHOLDER);
            }
            if (typeof(global::LightSwitchApplication.TP_VENDOR) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TP_VENDOR);
            }
            if (typeof(global::LightSwitchApplication.TP) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TP);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class APP :
        global::LightSwitchApplication.APP.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.APP.DetailsClass.IImplementation.REF_TECHNOLOGY
        {
            get
            {
                return this.REF_TECHNOLOGY;
            }
            set
            {
                this.REF_TECHNOLOGY = (global::LightSwitchApplication.Implementation.REF_TECHNOLOGY)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("REF_TECHNOLOGY");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.APP.DetailsClass.IImplementation.TP_APPLICATIONs
        {
            get
            {
                return this.TP_APPLICATIONs;
            }
        }
        
        partial void OnTechnologyIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("REF_TECHNOLOGY");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class REF_APPLICATION_TYPE :
        global::LightSwitchApplication.REF_APPLICATION_TYPE.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.REF_APPLICATION_TYPE.DetailsClass.IImplementation.TPs
        {
            get
            {
                return this.TPs;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class REF_COMPLEXITY :
        global::LightSwitchApplication.REF_COMPLEXITY.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.REF_COMPLEXITY.DetailsClass.IImplementation.TPs
        {
            get
            {
                return this.TPs;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.REF_COMPLEXITY.DetailsClass.IImplementation.TPs1
        {
            get
            {
                return this.TPs1;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class REF_DOCUMENT_TYPE :
        global::LightSwitchApplication.REF_DOCUMENT_TYPE.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.REF_DOCUMENT_TYPE.DetailsClass.IImplementation.TP_DOCUMENT_LINKs
        {
            get
            {
                return this.TP_DOCUMENT_LINKs;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class REF_GAP :
        global::LightSwitchApplication.REF_GAP.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.REF_GAP.DetailsClass.IImplementation.TPs
        {
            get
            {
                return this.TPs;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.REF_GAP.DetailsClass.IImplementation.TPs1
        {
            get
            {
                return this.TPs1;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class REF_PHASE :
        global::LightSwitchApplication.REF_PHASE.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.REF_PHASE.DetailsClass.IImplementation.TP_PHASEs
        {
            get
            {
                return this.TP_PHASEs;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class REF_ROLE :
        global::LightSwitchApplication.REF_ROLE.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.REF_ROLE.DetailsClass.IImplementation.RESOURCEs
        {
            get
            {
                return this.RESOURCEs;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class REF_STAKEHOLDER :
        global::LightSwitchApplication.REF_STAKEHOLDER.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.REF_STAKEHOLDER.DetailsClass.IImplementation.TP_STAKEHOLDERs
        {
            get
            {
                return this.TP_STAKEHOLDERs;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class REF_STATUS :
        global::LightSwitchApplication.REF_STATUS.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.REF_STATUS.DetailsClass.IImplementation.RESOURCEs
        {
            get
            {
                return this.RESOURCEs;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class REF_TECHNOLOGY :
        global::LightSwitchApplication.REF_TECHNOLOGY.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.REF_TECHNOLOGY.DetailsClass.IImplementation.APPLICATIONs
        {
            get
            {
                return this.APPLICATIONs;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class REF_TECHNOLOGY_STACK :
        global::LightSwitchApplication.REF_TECHNOLOGY_STACK.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.REF_TECHNOLOGY_STACK.DetailsClass.IImplementation.TPs
        {
            get
            {
                return this.TPs;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class REF_VENDOR :
        global::LightSwitchApplication.REF_VENDOR.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.REF_VENDOR.DetailsClass.IImplementation.TP_VENDORs
        {
            get
            {
                return this.TP_VENDORs;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class RESOURCE :
        global::LightSwitchApplication.RESOURCE.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RESOURCE.DetailsClass.IImplementation.REF_ROLE
        {
            get
            {
                return this.REF_ROLE;
            }
            set
            {
                this.REF_ROLE = (global::LightSwitchApplication.Implementation.REF_ROLE)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("REF_ROLE");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RESOURCE.DetailsClass.IImplementation.REF_STATUS
        {
            get
            {
                return this.REF_STATUS;
            }
            set
            {
                this.REF_STATUS = (global::LightSwitchApplication.Implementation.REF_STATUS)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("REF_STATUS");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.RESOURCE.DetailsClass.IImplementation.TP_RESOURCE_ALLOCATIONs
        {
            get
            {
                return this.TP_RESOURCE_ALLOCATIONs;
            }
        }
        
        partial void OnRoleIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("REF_ROLE");
            }
        }
        
        partial void OnStatusIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("REF_STATUS");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TP_APPLICATION :
        global::LightSwitchApplication.TP_APPLICATION.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP_APPLICATION.DetailsClass.IImplementation.APP
        {
            get
            {
                return this.APP;
            }
            set
            {
                this.APP = (global::LightSwitchApplication.Implementation.APP)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("APP");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP_APPLICATION.DetailsClass.IImplementation.TP
        {
            get
            {
                return this.TP;
            }
            set
            {
                this.TP = (global::LightSwitchApplication.Implementation.TP)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("TP");
                }
            }
        }
        
        partial void OnApplicationIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("APP");
            }
        }
        
        partial void OnTpIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("TP");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TP_DOCUMENT_LINK :
        global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.IImplementation.REF_DOCUMENT_TYPE
        {
            get
            {
                return this.REF_DOCUMENT_TYPE;
            }
            set
            {
                this.REF_DOCUMENT_TYPE = (global::LightSwitchApplication.Implementation.REF_DOCUMENT_TYPE)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("REF_DOCUMENT_TYPE");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP_DOCUMENT_LINK.DetailsClass.IImplementation.TP
        {
            get
            {
                return this.TP;
            }
            set
            {
                this.TP = (global::LightSwitchApplication.Implementation.TP)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("TP");
                }
            }
        }
        
        partial void OnDocumentTypeIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("REF_DOCUMENT_TYPE");
            }
        }
        
        partial void OnTpIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("TP");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TP_PHASE :
        global::LightSwitchApplication.TP_PHASE.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP_PHASE.DetailsClass.IImplementation.TP
        {
            get
            {
                return this.TP;
            }
            set
            {
                this.TP = (global::LightSwitchApplication.Implementation.TP)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("TP");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP_PHASE.DetailsClass.IImplementation.REF_PHASE
        {
            get
            {
                return this.REF_PHASE;
            }
            set
            {
                this.REF_PHASE = (global::LightSwitchApplication.Implementation.REF_PHASE)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("REF_PHASE");
                }
            }
        }
        
        partial void OnTpIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("TP");
            }
        }
        
        partial void OnPhaseIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("REF_PHASE");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TP_RESOURCE_ALLOCATION :
        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.IImplementation.RESOURCE
        {
            get
            {
                return this.RESOURCE;
            }
            set
            {
                this.RESOURCE = (global::LightSwitchApplication.Implementation.RESOURCE)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("RESOURCE");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.IImplementation.TP
        {
            get
            {
                return this.TP;
            }
            set
            {
                this.TP = (global::LightSwitchApplication.Implementation.TP)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("TP");
                }
            }
        }
        
        partial void OnResourceIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("RESOURCE");
            }
        }
        
        partial void OnTpIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("TP");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TP_STAKEHOLDER :
        global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.IImplementation.REF_STAKEHOLDER
        {
            get
            {
                return this.REF_STAKEHOLDER;
            }
            set
            {
                this.REF_STAKEHOLDER = (global::LightSwitchApplication.Implementation.REF_STAKEHOLDER)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("REF_STAKEHOLDER");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP_STAKEHOLDER.DetailsClass.IImplementation.TP
        {
            get
            {
                return this.TP;
            }
            set
            {
                this.TP = (global::LightSwitchApplication.Implementation.TP)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("TP");
                }
            }
        }
        
        partial void OnStakeholderIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("REF_STAKEHOLDER");
            }
        }
        
        partial void OnTpIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("TP");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TP_VENDOR :
        global::LightSwitchApplication.TP_VENDOR.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP_VENDOR.DetailsClass.IImplementation.REF_VENDOR
        {
            get
            {
                return this.REF_VENDOR;
            }
            set
            {
                this.REF_VENDOR = (global::LightSwitchApplication.Implementation.REF_VENDOR)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("REF_VENDOR");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP_VENDOR.DetailsClass.IImplementation.TP
        {
            get
            {
                return this.TP;
            }
            set
            {
                this.TP = (global::LightSwitchApplication.Implementation.TP)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("TP");
                }
            }
        }
        
        partial void OnVendorIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("REF_VENDOR");
            }
        }
        
        partial void OnTpIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("TP");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TP :
        global::LightSwitchApplication.TP.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.TP.DetailsClass.IImplementation.TP_APPLICATIONs
        {
            get
            {
                return this.TP_APPLICATIONs;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.TP.DetailsClass.IImplementation.TP_DOCUMENT_LINKs
        {
            get
            {
                return this.TP_DOCUMENT_LINKs;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.TP.DetailsClass.IImplementation.TP_PHASEs
        {
            get
            {
                return this.TP_PHASEs;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP.DetailsClass.IImplementation.REF_APPLICATION_TYPE
        {
            get
            {
                return this.REF_APPLICATION_TYPE;
            }
            set
            {
                this.REF_APPLICATION_TYPE = (global::LightSwitchApplication.Implementation.REF_APPLICATION_TYPE)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("REF_APPLICATION_TYPE");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP.DetailsClass.IImplementation.REF_COMPLEXITY
        {
            get
            {
                return this.REF_COMPLEXITY;
            }
            set
            {
                this.REF_COMPLEXITY = (global::LightSwitchApplication.Implementation.REF_COMPLEXITY)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("REF_COMPLEXITY");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP.DetailsClass.IImplementation.REF_COMPLEXITY1
        {
            get
            {
                return this.REF_COMPLEXITY1;
            }
            set
            {
                this.REF_COMPLEXITY1 = (global::LightSwitchApplication.Implementation.REF_COMPLEXITY)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("REF_COMPLEXITY1");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP.DetailsClass.IImplementation.REF_GAP
        {
            get
            {
                return this.REF_GAP;
            }
            set
            {
                this.REF_GAP = (global::LightSwitchApplication.Implementation.REF_GAP)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("REF_GAP");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP.DetailsClass.IImplementation.REF_GAP1
        {
            get
            {
                return this.REF_GAP1;
            }
            set
            {
                this.REF_GAP1 = (global::LightSwitchApplication.Implementation.REF_GAP)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("REF_GAP1");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TP.DetailsClass.IImplementation.REF_TECHNOLOGY_STACK
        {
            get
            {
                return this.REF_TECHNOLOGY_STACK;
            }
            set
            {
                this.REF_TECHNOLOGY_STACK = (global::LightSwitchApplication.Implementation.REF_TECHNOLOGY_STACK)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("REF_TECHNOLOGY_STACK");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.TP.DetailsClass.IImplementation.TP_RESOURCE_ALLOCATIONs
        {
            get
            {
                return this.TP_RESOURCE_ALLOCATIONs;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.TP.DetailsClass.IImplementation.TP_STAKEHOLDERs
        {
            get
            {
                return this.TP_STAKEHOLDERs;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.TP.DetailsClass.IImplementation.TP_VENDORs
        {
            get
            {
                return this.TP_VENDORs;
            }
        }
        
        partial void OnApplicationTypeIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("REF_APPLICATION_TYPE");
            }
        }
        
        partial void OnTechnicalComplexityIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("REF_COMPLEXITY");
            }
        }
        
        partial void OnForcedComplexityIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("REF_COMPLEXITY1");
            }
        }
        
        partial void OnTechnologyGapIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("REF_GAP");
            }
        }
        
        partial void OnFunctionalGapIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("REF_GAP1");
            }
        }
        
        partial void OnTechnologyStackIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("REF_TECHNOLOGY_STACK");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

