

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class TP_RESOURCE_ALLOCATION : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the TP_RESOURCE_ALLOCATION entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TP_RESOURCE_ALLOCATION()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TP_RESOURCE_ALLOCATION(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TP_RESOURCE_ALLOCATION_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TP_RESOURCE_ALLOCATION_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int TpResourceAllocationId
        {
            get
            {
                return global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.TpResourceAllocationId);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TpResourceAllocationId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TpResourceAllocationId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TpResourceAllocationId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<double> Percentage
        {
            get
            {
                return global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.Percentage);
            }
            set
            {
                global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.Percentage, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Percentage_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Percentage_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Percentage_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> PlannedStartDate
        {
            get
            {
                return global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.PlannedStartDate);
            }
            set
            {
                global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.PlannedStartDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlannedStartDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlannedStartDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlannedStartDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> PlannedEndDate
        {
            get
            {
                return global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.PlannedEndDate);
            }
            set
            {
                global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.PlannedEndDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlannedEndDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlannedEndDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PlannedEndDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.CreatedBy);
            }
            set
            {
                global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.CreatedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.CreatedDate);
            }
            set
            {
                global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.CreatedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.ModifiedBy);
            }
            set
            {
                global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.ModifiedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.RESOURCE RESOURCE
        {
            get
            {
                return global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.RESOURCE);
            }
            set
            {
                global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.RESOURCE, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RESOURCE_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RESOURCE_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RESOURCE_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.TP TP
        {
            get
            {
                return global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.GetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.TP);
            }
            set
            {
                global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.SetValue(this, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.TP, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TP_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TP_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TP_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.TP_RESOURCE_ALLOCATION,
                global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass,
                global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.IImplementation,
                global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.TpResourceAllocationId;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass>.Entry
                __TP_RESOURCE_ALLOCATIONEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass>.Entry(
                    global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.__TP_RESOURCE_ALLOCATION_CreateNew,
                    global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.__TP_RESOURCE_ALLOCATION_Created,
                    global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.__TP_RESOURCE_ALLOCATION_AllowSaveWithErrors);
            private static global::LightSwitchApplication.TP_RESOURCE_ALLOCATION __TP_RESOURCE_ALLOCATION_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION> es)
            {
                return new global::LightSwitchApplication.TP_RESOURCE_ALLOCATION(es);
            }
            private static void __TP_RESOURCE_ALLOCATION_Created(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
            {
                e.TP_RESOURCE_ALLOCATION_Created();
            }
            private static bool __TP_RESOURCE_ALLOCATION_AllowSaveWithErrors(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
            {
                bool result = false;
                e.TP_RESOURCE_ALLOCATION_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, int> TpResourceAllocationId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.TpResourceAllocationId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<double>> Percentage
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.Percentage) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<double>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>> PlannedStartDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.PlannedStartDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>> PlannedEndDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.PlannedEndDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>> CreatedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.CreatedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::LightSwitchApplication.RESOURCE> RESOURCE
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.RESOURCE) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::LightSwitchApplication.RESOURCE>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::LightSwitchApplication.TP> TP
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.TP) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::LightSwitchApplication.TP>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int TpResourceAllocationId { get; }
                new global::System.Nullable<double> Percentage { get; set; }
                new global::System.Nullable<global::System.DateTime> PlannedStartDate { get; set; }
                new global::System.Nullable<global::System.DateTime> PlannedEndDate { get; set; }
                new string CreatedBy { get; set; }
                new global::System.Nullable<global::System.DateTime> CreatedDate { get; set; }
                new global::System.Nullable<global::System.DateTime> ModifiedDate { get; set; }
                new string ModifiedBy { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation RESOURCE { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation TP { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, int>.Entry
                    TpResourceAllocationId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, int>.Entry(
                        "TpResourceAllocationId",
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._TpResourceAllocationId_Stub,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._TpResourceAllocationId_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._TpResourceAllocationId_Validate,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._TpResourceAllocationId_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._TpResourceAllocationId_OnValueChanged);
                private static void _TpResourceAllocationId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, int>.Data> c, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, object sf)
                {
                    c(d, ref d._TpResourceAllocationId, sf);
                }
                private static bool _TpResourceAllocationId_ComputeIsReadOnly(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    bool result = false;
                    e.TpResourceAllocationId_IsReadOnly(ref result);
                    return result;
                }
                private static void _TpResourceAllocationId_Validate(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TpResourceAllocationId_Validate(r);
                }
                private static int _TpResourceAllocationId_GetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d)
                {
                    return d.ImplementationEntity.TpResourceAllocationId;
                }
                private static void _TpResourceAllocationId_OnValueChanged(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    e.TpResourceAllocationId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<double>>.Entry
                    Percentage = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<double>>.Entry(
                        "Percentage",
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._Percentage_Stub,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._Percentage_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._Percentage_Validate,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._Percentage_GetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._Percentage_SetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._Percentage_OnValueChanged);
                private static void _Percentage_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<double>>.Data> c, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, object sf)
                {
                    c(d, ref d._Percentage, sf);
                }
                private static bool _Percentage_ComputeIsReadOnly(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    bool result = false;
                    e.Percentage_IsReadOnly(ref result);
                    return result;
                }
                private static void _Percentage_Validate(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Percentage_Validate(r);
                }
                private static global::System.Nullable<double> _Percentage_GetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d)
                {
                    return d.ImplementationEntity.Percentage;
                }
                private static void _Percentage_SetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, global::System.Nullable<double> v)
                {
                    d.ImplementationEntity.Percentage = v;
                }
                private static void _Percentage_OnValueChanged(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    e.Percentage_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    PlannedStartDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "PlannedStartDate",
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._PlannedStartDate_Stub,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._PlannedStartDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._PlannedStartDate_Validate,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._PlannedStartDate_GetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._PlannedStartDate_SetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._PlannedStartDate_OnValueChanged);
                private static void _PlannedStartDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, object sf)
                {
                    c(d, ref d._PlannedStartDate, sf);
                }
                private static bool _PlannedStartDate_ComputeIsReadOnly(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    bool result = false;
                    e.PlannedStartDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _PlannedStartDate_Validate(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PlannedStartDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _PlannedStartDate_GetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d)
                {
                    return d.ImplementationEntity.PlannedStartDate;
                }
                private static void _PlannedStartDate_SetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.PlannedStartDate = global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.TruncateDate(v);
                }
                private static void _PlannedStartDate_OnValueChanged(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    e.PlannedStartDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    PlannedEndDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "PlannedEndDate",
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._PlannedEndDate_Stub,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._PlannedEndDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._PlannedEndDate_Validate,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._PlannedEndDate_GetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._PlannedEndDate_SetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._PlannedEndDate_OnValueChanged);
                private static void _PlannedEndDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, object sf)
                {
                    c(d, ref d._PlannedEndDate, sf);
                }
                private static bool _PlannedEndDate_ComputeIsReadOnly(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    bool result = false;
                    e.PlannedEndDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _PlannedEndDate_Validate(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PlannedEndDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _PlannedEndDate_GetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d)
                {
                    return d.ImplementationEntity.PlannedEndDate;
                }
                private static void _PlannedEndDate_SetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.PlannedEndDate = global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.TruncateDate(v);
                }
                private static void _PlannedEndDate_OnValueChanged(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    e.PlannedEndDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._CreatedBy_SetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, string>.Data> c, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_SetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CreatedBy = v;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    CreatedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "CreatedDate",
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._CreatedDate_Stub,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._CreatedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._CreatedDate_Validate,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._CreatedDate_GetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._CreatedDate_SetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._CreatedDate_OnValueChanged);
                private static void _CreatedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedDate, sf);
                }
                private static bool _CreatedDate_ComputeIsReadOnly(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    bool result = false;
                    e.CreatedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedDate_Validate(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _CreatedDate_GetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedDate;
                }
                private static void _CreatedDate_SetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.CreatedDate = global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreatedDate_OnValueChanged(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    e.CreatedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    e.ModifiedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._ModifiedBy_SetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, string>.Data> c, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_SetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ModifiedBy = v;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::LightSwitchApplication.RESOURCE>.Entry
                    RESOURCE = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::LightSwitchApplication.RESOURCE>.Entry(
                        "RESOURCE",
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._RESOURCE_Stub,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._RESOURCE_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._RESOURCE_Validate,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._RESOURCE_GetCoreImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._RESOURCE_GetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._RESOURCE_SetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._RESOURCE_Refresh,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._RESOURCE_OnValueChanged);
                private static void _RESOURCE_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::LightSwitchApplication.RESOURCE>.Data> c, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, object sf)
                {
                    c(d, ref d._RESOURCE, sf);
                }
                private static bool _RESOURCE_ComputeIsReadOnly(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    bool result = false;
                    e.RESOURCE_IsReadOnly(ref result);
                    return result;
                }
                private static void _RESOURCE_Validate(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RESOURCE_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _RESOURCE_GetCoreImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d)
                {
                    return d.ImplementationEntity.RESOURCE;
                }
                private static global::LightSwitchApplication.RESOURCE _RESOURCE_GetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass>(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.RESOURCE, ref d._RESOURCE);
                }
                private static void _RESOURCE_SetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, global::LightSwitchApplication.RESOURCE v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.RESOURCE, ref d._RESOURCE, (i, ev) => i.RESOURCE = ev, v);
                }
                private static void _RESOURCE_Refresh(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.RESOURCE, ref d._RESOURCE);
                }
                private static void _RESOURCE_OnValueChanged(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    e.RESOURCE_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::LightSwitchApplication.TP>.Entry
                    TP = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::LightSwitchApplication.TP>.Entry(
                        "TP",
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._TP_Stub,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._TP_ComputeIsReadOnly,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._TP_Validate,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._TP_GetCoreImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._TP_GetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._TP_SetImplementationValue,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._TP_Refresh,
                        global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties._TP_OnValueChanged);
                private static void _TP_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::LightSwitchApplication.TP>.Data> c, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, object sf)
                {
                    c(d, ref d._TP, sf);
                }
                private static bool _TP_ComputeIsReadOnly(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    bool result = false;
                    e.TP_IsReadOnly(ref result);
                    return result;
                }
                private static void _TP_Validate(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TP_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _TP_GetCoreImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d)
                {
                    return d.ImplementationEntity.TP;
                }
                private static global::LightSwitchApplication.TP _TP_GetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.TP, global::LightSwitchApplication.TP.DetailsClass>(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.TP, ref d._TP);
                }
                private static void _TP_SetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d, global::LightSwitchApplication.TP v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.TP, ref d._TP, (i, ev) => i.TP = ev, v);
                }
                private static void _TP_Refresh(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass.PropertySetProperties.TP, ref d._TP);
                }
                private static void _TP_OnValueChanged(global::LightSwitchApplication.TP_RESOURCE_ALLOCATION e)
                {
                    e.TP_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, int>.Data _TpResourceAllocationId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<double>>.Data _Percentage;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _PlannedStartDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _PlannedEndDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _CreatedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _ModifiedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::LightSwitchApplication.RESOURCE>.Data _RESOURCE;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass, global::LightSwitchApplication.TP>.Data _TP;
            
        }
    
        #endregion
    }
    
    #endregion
}
