

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class APP : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the APP entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public APP()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public APP(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.APP> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.APP.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void APP_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void APP_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public short ApplicationID
        {
            get
            {
                return global::LightSwitchApplication.APP.DetailsClass.GetValue(this, global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.ApplicationID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.APP.DetailsClass.GetValue(this, global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.APP.DetailsClass.SetValue(this, global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.APP.DetailsClass.GetValue(this, global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.CreatedBy);
            }
            set
            {
                global::LightSwitchApplication.APP.DetailsClass.SetValue(this, global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.CreatedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return global::LightSwitchApplication.APP.DetailsClass.GetValue(this, global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.CreatedDate);
            }
            set
            {
                global::LightSwitchApplication.APP.DetailsClass.SetValue(this, global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.CreatedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.APP.DetailsClass.GetValue(this, global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.ModifiedBy);
            }
            set
            {
                global::LightSwitchApplication.APP.DetailsClass.SetValue(this, global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.ModifiedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.APP.DetailsClass.GetValue(this, global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.APP.DetailsClass.SetValue(this, global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.REF_TECHNOLOGY REF_TECHNOLOGY
        {
            get
            {
                return global::LightSwitchApplication.APP.DetailsClass.GetValue(this, global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.REF_TECHNOLOGY);
            }
            set
            {
                global::LightSwitchApplication.APP.DetailsClass.SetValue(this, global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.REF_TECHNOLOGY, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_TECHNOLOGY_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_TECHNOLOGY_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_TECHNOLOGY_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.TP_APPLICATION> TP_APPLICATIONs
        {
            get
            {
                return global::LightSwitchApplication.APP.DetailsClass.GetValue(this, global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.TP_APPLICATIONs);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.TP_APPLICATION> TP_APPLICATIONsQuery
        {
            get
            {
                return global::LightSwitchApplication.APP.DetailsClass.GetQuery(this, global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.TP_APPLICATIONs);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.APP,
                global::LightSwitchApplication.APP.DetailsClass,
                global::LightSwitchApplication.APP.DetailsClass.IImplementation,
                global::LightSwitchApplication.APP.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.ApplicationID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass>.Entry
                __APPEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass>.Entry(
                    global::LightSwitchApplication.APP.DetailsClass.__APP_CreateNew,
                    global::LightSwitchApplication.APP.DetailsClass.__APP_Created,
                    global::LightSwitchApplication.APP.DetailsClass.__APP_AllowSaveWithErrors);
            private static global::LightSwitchApplication.APP __APP_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.APP> es)
            {
                return new global::LightSwitchApplication.APP(es);
            }
            private static void __APP_Created(global::LightSwitchApplication.APP e)
            {
                e.APP_Created();
            }
            private static bool __APP_AllowSaveWithErrors(global::LightSwitchApplication.APP e)
            {
                bool result = false;
                e.APP_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.APP.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, short> ApplicationID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.ApplicationID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, short>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::System.Nullable<global::System.DateTime>> CreatedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.CreatedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::System.Nullable<global::System.DateTime>> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::LightSwitchApplication.REF_TECHNOLOGY> REF_TECHNOLOGY
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.REF_TECHNOLOGY) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::LightSwitchApplication.REF_TECHNOLOGY>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::LightSwitchApplication.TP_APPLICATION> TP_APPLICATIONs
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.TP_APPLICATIONs) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::LightSwitchApplication.TP_APPLICATION>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new short ApplicationID { get; }
                new string Name { get; set; }
                new string CreatedBy { get; set; }
                new global::System.Nullable<global::System.DateTime> CreatedDate { get; set; }
                new string ModifiedBy { get; set; }
                new global::System.Nullable<global::System.DateTime> ModifiedDate { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation REF_TECHNOLOGY { get; set; }
                new global::System.Collections.IEnumerable TP_APPLICATIONs { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, short>.Entry
                    ApplicationID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, short>.Entry(
                        "ApplicationID",
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ApplicationID_Stub,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ApplicationID_ComputeIsReadOnly,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ApplicationID_Validate,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ApplicationID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ApplicationID_OnValueChanged);
                private static void _ApplicationID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.APP.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, short>.Data> c, global::LightSwitchApplication.APP.DetailsClass d, object sf)
                {
                    c(d, ref d._ApplicationID, sf);
                }
                private static bool _ApplicationID_ComputeIsReadOnly(global::LightSwitchApplication.APP e)
                {
                    bool result = false;
                    e.ApplicationID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ApplicationID_Validate(global::LightSwitchApplication.APP e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ApplicationID_Validate(r);
                }
                private static short _ApplicationID_GetImplementationValue(global::LightSwitchApplication.APP.DetailsClass d)
                {
                    return d.ImplementationEntity.ApplicationID;
                }
                private static void _ApplicationID_OnValueChanged(global::LightSwitchApplication.APP e)
                {
                    e.ApplicationID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.APP.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string>.Data> c, global::LightSwitchApplication.APP.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.APP e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.APP e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.APP.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.APP.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.APP e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._CreatedBy_SetImplementationValue,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.APP.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string>.Data> c, global::LightSwitchApplication.APP.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.APP e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.APP e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.APP.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_SetImplementationValue(global::LightSwitchApplication.APP.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CreatedBy = v;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.APP e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    CreatedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "CreatedDate",
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._CreatedDate_Stub,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._CreatedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._CreatedDate_Validate,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._CreatedDate_GetImplementationValue,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._CreatedDate_SetImplementationValue,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._CreatedDate_OnValueChanged);
                private static void _CreatedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.APP.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.APP.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedDate, sf);
                }
                private static bool _CreatedDate_ComputeIsReadOnly(global::LightSwitchApplication.APP e)
                {
                    bool result = false;
                    e.CreatedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedDate_Validate(global::LightSwitchApplication.APP e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _CreatedDate_GetImplementationValue(global::LightSwitchApplication.APP.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedDate;
                }
                private static void _CreatedDate_SetImplementationValue(global::LightSwitchApplication.APP.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.CreatedDate = global::LightSwitchApplication.APP.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreatedDate_OnValueChanged(global::LightSwitchApplication.APP e)
                {
                    e.CreatedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ModifiedBy_SetImplementationValue,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.APP.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string>.Data> c, global::LightSwitchApplication.APP.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.APP e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.APP e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.APP.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_SetImplementationValue(global::LightSwitchApplication.APP.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ModifiedBy = v;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.APP e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.APP.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.APP.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.APP e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.APP e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.APP.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.APP.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.APP.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.APP e)
                {
                    e.ModifiedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::LightSwitchApplication.REF_TECHNOLOGY>.Entry
                    REF_TECHNOLOGY = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::LightSwitchApplication.REF_TECHNOLOGY>.Entry(
                        "REF_TECHNOLOGY",
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._REF_TECHNOLOGY_Stub,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._REF_TECHNOLOGY_ComputeIsReadOnly,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._REF_TECHNOLOGY_Validate,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._REF_TECHNOLOGY_GetCoreImplementationValue,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._REF_TECHNOLOGY_GetImplementationValue,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._REF_TECHNOLOGY_SetImplementationValue,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._REF_TECHNOLOGY_Refresh,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._REF_TECHNOLOGY_OnValueChanged);
                private static void _REF_TECHNOLOGY_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.APP.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::LightSwitchApplication.REF_TECHNOLOGY>.Data> c, global::LightSwitchApplication.APP.DetailsClass d, object sf)
                {
                    c(d, ref d._REF_TECHNOLOGY, sf);
                }
                private static bool _REF_TECHNOLOGY_ComputeIsReadOnly(global::LightSwitchApplication.APP e)
                {
                    bool result = false;
                    e.REF_TECHNOLOGY_IsReadOnly(ref result);
                    return result;
                }
                private static void _REF_TECHNOLOGY_Validate(global::LightSwitchApplication.APP e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.REF_TECHNOLOGY_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _REF_TECHNOLOGY_GetCoreImplementationValue(global::LightSwitchApplication.APP.DetailsClass d)
                {
                    return d.ImplementationEntity.REF_TECHNOLOGY;
                }
                private static global::LightSwitchApplication.REF_TECHNOLOGY _REF_TECHNOLOGY_GetImplementationValue(global::LightSwitchApplication.APP.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.REF_TECHNOLOGY, global::LightSwitchApplication.REF_TECHNOLOGY.DetailsClass>(global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.REF_TECHNOLOGY, ref d._REF_TECHNOLOGY);
                }
                private static void _REF_TECHNOLOGY_SetImplementationValue(global::LightSwitchApplication.APP.DetailsClass d, global::LightSwitchApplication.REF_TECHNOLOGY v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.REF_TECHNOLOGY, ref d._REF_TECHNOLOGY, (i, ev) => i.REF_TECHNOLOGY = ev, v);
                }
                private static void _REF_TECHNOLOGY_Refresh(global::LightSwitchApplication.APP.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.REF_TECHNOLOGY, ref d._REF_TECHNOLOGY);
                }
                private static void _REF_TECHNOLOGY_OnValueChanged(global::LightSwitchApplication.APP e)
                {
                    e.REF_TECHNOLOGY_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::LightSwitchApplication.TP_APPLICATION>.Entry
                    TP_APPLICATIONs = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::LightSwitchApplication.TP_APPLICATION>.Entry(
                        "TP_APPLICATIONs",
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._TP_APPLICATIONs_Stub,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._TP_APPLICATIONs_GetReferencedEntities,
                        global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties._TP_APPLICATIONs_GetEntityCollection);
                private static void _TP_APPLICATIONs_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.APP.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::LightSwitchApplication.TP_APPLICATION>.Data> c, global::LightSwitchApplication.APP.DetailsClass d, object sf)
                {
                    c(d, ref d._TP_APPLICATIONs, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.TP_APPLICATION> _TP_APPLICATIONs_GetReferencedEntities(global::LightSwitchApplication.APP.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.TP_APPLICATION, global::LightSwitchApplication.TP_APPLICATION.DetailsClass>(global::LightSwitchApplication.APP.DetailsClass.PropertySetProperties.TP_APPLICATIONs, ref d._TP_APPLICATIONs);
                }
                private static global::System.Collections.IEnumerable _TP_APPLICATIONs_GetEntityCollection(global::LightSwitchApplication.APP.DetailsClass d)
                {
                    return d.ImplementationEntity.TP_APPLICATIONs;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, short>.Data _ApplicationID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _CreatedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _ModifiedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::LightSwitchApplication.REF_TECHNOLOGY>.Data _REF_TECHNOLOGY;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.APP, global::LightSwitchApplication.APP.DetailsClass, global::LightSwitchApplication.TP_APPLICATION>.Data _TP_APPLICATIONs;
            
        }
    
        #endregion
    }
    
    #endregion
}
