

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class RESOURCE : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the RESOURCE entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public RESOURCE()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public RESOURCE(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.RESOURCE> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.RESOURCE.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RESOURCE_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RESOURCE_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ResourceID
        {
            get
            {
                return global::LightSwitchApplication.RESOURCE.DetailsClass.GetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.ResourceID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResourceID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResourceID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResourceID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.RESOURCE.DetailsClass.GetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.RESOURCE.DetailsClass.SetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string EmailId
        {
            get
            {
                return global::LightSwitchApplication.RESOURCE.DetailsClass.GetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.EmailId);
            }
            set
            {
                global::LightSwitchApplication.RESOURCE.DetailsClass.SetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.EmailId, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmailId_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmailId_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EmailId_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.RESOURCE.DetailsClass.GetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.CreatedBy);
            }
            set
            {
                global::LightSwitchApplication.RESOURCE.DetailsClass.SetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.CreatedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> CreatedDate
        {
            get
            {
                return global::LightSwitchApplication.RESOURCE.DetailsClass.GetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.CreatedDate);
            }
            set
            {
                global::LightSwitchApplication.RESOURCE.DetailsClass.SetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.CreatedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return global::LightSwitchApplication.RESOURCE.DetailsClass.GetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.ModifiedDate);
            }
            set
            {
                global::LightSwitchApplication.RESOURCE.DetailsClass.SetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.ModifiedDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.RESOURCE.DetailsClass.GetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.ModifiedBy);
            }
            set
            {
                global::LightSwitchApplication.RESOURCE.DetailsClass.SetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.ModifiedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.REF_ROLE REF_ROLE
        {
            get
            {
                return global::LightSwitchApplication.RESOURCE.DetailsClass.GetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.REF_ROLE);
            }
            set
            {
                global::LightSwitchApplication.RESOURCE.DetailsClass.SetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.REF_ROLE, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_ROLE_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_ROLE_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_ROLE_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.REF_STATUS REF_STATUS
        {
            get
            {
                return global::LightSwitchApplication.RESOURCE.DetailsClass.GetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.REF_STATUS);
            }
            set
            {
                global::LightSwitchApplication.RESOURCE.DetailsClass.SetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.REF_STATUS, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_STATUS_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_STATUS_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void REF_STATUS_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION> TP_RESOURCE_ALLOCATIONs
        {
            get
            {
                return global::LightSwitchApplication.RESOURCE.DetailsClass.GetValue(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.TP_RESOURCE_ALLOCATIONs);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION> TP_RESOURCE_ALLOCATIONsQuery
        {
            get
            {
                return global::LightSwitchApplication.RESOURCE.DetailsClass.GetQuery(this, global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.TP_RESOURCE_ALLOCATIONs);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.RESOURCE,
                global::LightSwitchApplication.RESOURCE.DetailsClass,
                global::LightSwitchApplication.RESOURCE.DetailsClass.IImplementation,
                global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.ResourceID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass>.Entry
                __RESOURCEEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass>.Entry(
                    global::LightSwitchApplication.RESOURCE.DetailsClass.__RESOURCE_CreateNew,
                    global::LightSwitchApplication.RESOURCE.DetailsClass.__RESOURCE_Created,
                    global::LightSwitchApplication.RESOURCE.DetailsClass.__RESOURCE_AllowSaveWithErrors);
            private static global::LightSwitchApplication.RESOURCE __RESOURCE_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.RESOURCE> es)
            {
                return new global::LightSwitchApplication.RESOURCE(es);
            }
            private static void __RESOURCE_Created(global::LightSwitchApplication.RESOURCE e)
            {
                e.RESOURCE_Created();
            }
            private static bool __RESOURCE_AllowSaveWithErrors(global::LightSwitchApplication.RESOURCE e)
            {
                bool result = false;
                e.RESOURCE_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, int> ResourceID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.ResourceID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string> EmailId
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.EmailId) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::System.Nullable<global::System.DateTime>> CreatedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.CreatedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::System.Nullable<global::System.DateTime>> ModifiedDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.ModifiedDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.REF_ROLE> REF_ROLE
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.REF_ROLE) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.REF_ROLE>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.REF_STATUS> REF_STATUS
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.REF_STATUS) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.REF_STATUS>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION> TP_RESOURCE_ALLOCATIONs
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.TP_RESOURCE_ALLOCATIONs) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ResourceID { get; }
                new string Name { get; set; }
                new string EmailId { get; set; }
                new string CreatedBy { get; set; }
                new global::System.Nullable<global::System.DateTime> CreatedDate { get; set; }
                new global::System.Nullable<global::System.DateTime> ModifiedDate { get; set; }
                new string ModifiedBy { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation REF_ROLE { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation REF_STATUS { get; set; }
                new global::System.Collections.IEnumerable TP_RESOURCE_ALLOCATIONs { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, int>.Entry
                    ResourceID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, int>.Entry(
                        "ResourceID",
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ResourceID_Stub,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ResourceID_ComputeIsReadOnly,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ResourceID_Validate,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ResourceID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ResourceID_OnValueChanged);
                private static void _ResourceID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RESOURCE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, int>.Data> c, global::LightSwitchApplication.RESOURCE.DetailsClass d, object sf)
                {
                    c(d, ref d._ResourceID, sf);
                }
                private static bool _ResourceID_ComputeIsReadOnly(global::LightSwitchApplication.RESOURCE e)
                {
                    bool result = false;
                    e.ResourceID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ResourceID_Validate(global::LightSwitchApplication.RESOURCE e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ResourceID_Validate(r);
                }
                private static int _ResourceID_GetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d)
                {
                    return d.ImplementationEntity.ResourceID;
                }
                private static void _ResourceID_OnValueChanged(global::LightSwitchApplication.RESOURCE e)
                {
                    e.ResourceID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RESOURCE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Data> c, global::LightSwitchApplication.RESOURCE.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.RESOURCE e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.RESOURCE e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.RESOURCE e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Entry
                    EmailId = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Entry(
                        "EmailId",
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._EmailId_Stub,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._EmailId_ComputeIsReadOnly,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._EmailId_Validate,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._EmailId_GetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._EmailId_SetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._EmailId_OnValueChanged);
                private static void _EmailId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RESOURCE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Data> c, global::LightSwitchApplication.RESOURCE.DetailsClass d, object sf)
                {
                    c(d, ref d._EmailId, sf);
                }
                private static bool _EmailId_ComputeIsReadOnly(global::LightSwitchApplication.RESOURCE e)
                {
                    bool result = false;
                    e.EmailId_IsReadOnly(ref result);
                    return result;
                }
                private static void _EmailId_Validate(global::LightSwitchApplication.RESOURCE e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EmailId_Validate(r);
                }
                private static string _EmailId_GetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d)
                {
                    return d.ImplementationEntity.EmailId;
                }
                private static void _EmailId_SetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d, string v)
                {
                    d.ImplementationEntity.EmailId = v;
                }
                private static void _EmailId_OnValueChanged(global::LightSwitchApplication.RESOURCE e)
                {
                    e.EmailId_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._CreatedBy_SetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RESOURCE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Data> c, global::LightSwitchApplication.RESOURCE.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.RESOURCE e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.RESOURCE e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_SetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d, string v)
                {
                    d.ImplementationEntity.CreatedBy = v;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.RESOURCE e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    CreatedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "CreatedDate",
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._CreatedDate_Stub,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._CreatedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._CreatedDate_Validate,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._CreatedDate_GetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._CreatedDate_SetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._CreatedDate_OnValueChanged);
                private static void _CreatedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RESOURCE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.RESOURCE.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedDate, sf);
                }
                private static bool _CreatedDate_ComputeIsReadOnly(global::LightSwitchApplication.RESOURCE e)
                {
                    bool result = false;
                    e.CreatedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedDate_Validate(global::LightSwitchApplication.RESOURCE e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _CreatedDate_GetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedDate;
                }
                private static void _CreatedDate_SetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.CreatedDate = global::LightSwitchApplication.RESOURCE.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _CreatedDate_OnValueChanged(global::LightSwitchApplication.RESOURCE e)
                {
                    e.CreatedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    ModifiedDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "ModifiedDate",
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ModifiedDate_Stub,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ModifiedDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ModifiedDate_Validate,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ModifiedDate_GetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ModifiedDate_SetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ModifiedDate_OnValueChanged);
                private static void _ModifiedDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RESOURCE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.RESOURCE.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedDate, sf);
                }
                private static bool _ModifiedDate_ComputeIsReadOnly(global::LightSwitchApplication.RESOURCE e)
                {
                    bool result = false;
                    e.ModifiedDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedDate_Validate(global::LightSwitchApplication.RESOURCE e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedDate_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _ModifiedDate_GetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedDate;
                }
                private static void _ModifiedDate_SetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.ModifiedDate = global::LightSwitchApplication.RESOURCE.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _ModifiedDate_OnValueChanged(global::LightSwitchApplication.RESOURCE e)
                {
                    e.ModifiedDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ModifiedBy_SetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RESOURCE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Data> c, global::LightSwitchApplication.RESOURCE.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.RESOURCE e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.RESOURCE e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_SetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ModifiedBy = v;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.RESOURCE e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.REF_ROLE>.Entry
                    REF_ROLE = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.REF_ROLE>.Entry(
                        "REF_ROLE",
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_ROLE_Stub,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_ROLE_ComputeIsReadOnly,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_ROLE_Validate,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_ROLE_GetCoreImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_ROLE_GetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_ROLE_SetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_ROLE_Refresh,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_ROLE_OnValueChanged);
                private static void _REF_ROLE_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RESOURCE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.REF_ROLE>.Data> c, global::LightSwitchApplication.RESOURCE.DetailsClass d, object sf)
                {
                    c(d, ref d._REF_ROLE, sf);
                }
                private static bool _REF_ROLE_ComputeIsReadOnly(global::LightSwitchApplication.RESOURCE e)
                {
                    bool result = false;
                    e.REF_ROLE_IsReadOnly(ref result);
                    return result;
                }
                private static void _REF_ROLE_Validate(global::LightSwitchApplication.RESOURCE e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.REF_ROLE_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _REF_ROLE_GetCoreImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d)
                {
                    return d.ImplementationEntity.REF_ROLE;
                }
                private static global::LightSwitchApplication.REF_ROLE _REF_ROLE_GetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.REF_ROLE, global::LightSwitchApplication.REF_ROLE.DetailsClass>(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.REF_ROLE, ref d._REF_ROLE);
                }
                private static void _REF_ROLE_SetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d, global::LightSwitchApplication.REF_ROLE v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.REF_ROLE, ref d._REF_ROLE, (i, ev) => i.REF_ROLE = ev, v);
                }
                private static void _REF_ROLE_Refresh(global::LightSwitchApplication.RESOURCE.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.REF_ROLE, ref d._REF_ROLE);
                }
                private static void _REF_ROLE_OnValueChanged(global::LightSwitchApplication.RESOURCE e)
                {
                    e.REF_ROLE_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.REF_STATUS>.Entry
                    REF_STATUS = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.REF_STATUS>.Entry(
                        "REF_STATUS",
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_STATUS_Stub,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_STATUS_ComputeIsReadOnly,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_STATUS_Validate,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_STATUS_GetCoreImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_STATUS_GetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_STATUS_SetImplementationValue,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_STATUS_Refresh,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._REF_STATUS_OnValueChanged);
                private static void _REF_STATUS_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RESOURCE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.REF_STATUS>.Data> c, global::LightSwitchApplication.RESOURCE.DetailsClass d, object sf)
                {
                    c(d, ref d._REF_STATUS, sf);
                }
                private static bool _REF_STATUS_ComputeIsReadOnly(global::LightSwitchApplication.RESOURCE e)
                {
                    bool result = false;
                    e.REF_STATUS_IsReadOnly(ref result);
                    return result;
                }
                private static void _REF_STATUS_Validate(global::LightSwitchApplication.RESOURCE e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.REF_STATUS_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _REF_STATUS_GetCoreImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d)
                {
                    return d.ImplementationEntity.REF_STATUS;
                }
                private static global::LightSwitchApplication.REF_STATUS _REF_STATUS_GetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.REF_STATUS, global::LightSwitchApplication.REF_STATUS.DetailsClass>(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.REF_STATUS, ref d._REF_STATUS);
                }
                private static void _REF_STATUS_SetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass d, global::LightSwitchApplication.REF_STATUS v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.REF_STATUS, ref d._REF_STATUS, (i, ev) => i.REF_STATUS = ev, v);
                }
                private static void _REF_STATUS_Refresh(global::LightSwitchApplication.RESOURCE.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.REF_STATUS, ref d._REF_STATUS);
                }
                private static void _REF_STATUS_OnValueChanged(global::LightSwitchApplication.RESOURCE e)
                {
                    e.REF_STATUS_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION>.Entry
                    TP_RESOURCE_ALLOCATIONs = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION>.Entry(
                        "TP_RESOURCE_ALLOCATIONs",
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._TP_RESOURCE_ALLOCATIONs_Stub,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._TP_RESOURCE_ALLOCATIONs_GetReferencedEntities,
                        global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties._TP_RESOURCE_ALLOCATIONs_GetEntityCollection);
                private static void _TP_RESOURCE_ALLOCATIONs_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.RESOURCE.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION>.Data> c, global::LightSwitchApplication.RESOURCE.DetailsClass d, object sf)
                {
                    c(d, ref d._TP_RESOURCE_ALLOCATIONs, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION> _TP_RESOURCE_ALLOCATIONs_GetReferencedEntities(global::LightSwitchApplication.RESOURCE.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.TP_RESOURCE_ALLOCATION, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION.DetailsClass>(global::LightSwitchApplication.RESOURCE.DetailsClass.PropertySetProperties.TP_RESOURCE_ALLOCATIONs, ref d._TP_RESOURCE_ALLOCATIONs);
                }
                private static global::System.Collections.IEnumerable _TP_RESOURCE_ALLOCATIONs_GetEntityCollection(global::LightSwitchApplication.RESOURCE.DetailsClass d)
                {
                    return d.ImplementationEntity.TP_RESOURCE_ALLOCATIONs;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, int>.Data _ResourceID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Data _EmailId;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _CreatedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _ModifiedDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.REF_ROLE>.Data _REF_ROLE;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.REF_STATUS>.Data _REF_STATUS;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.RESOURCE, global::LightSwitchApplication.RESOURCE.DetailsClass, global::LightSwitchApplication.TP_RESOURCE_ALLOCATION>.Data _TP_RESOURCE_ALLOCATIONs;
            
        }
    
        #endregion
    }
    
    #endregion
}
