// Warning: AutoGenerated file, Don't edit.
document.writeln("<script type=\"text/javascript\" src=\"Screens/Reference/Role/ViewRole.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Reference/Status/ViewStatus.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Reference/Technology/ViewTechnology.lsml.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"Screens/Resource/ViewResourceDetail.lsml.js\"></script>");
